### ISSUE TITLE
Cannot replicate because the master purged required binary logs

### ISSUE THREAD

**Issue by shunki-fujita** [cybozu-go/moco#731] opened 2024-08-21 06:59 UTC
**Describe the bug**
Binary logs may be missing under the following conditions:
  - Initialize and rebuild primary pod with CLONE
  - Replication delays are occurring and the primary pod does not have the binlog that the replica pod requires.
 
Executing the `CHANGE MASTER TO` command will delete relay logs.
If there are transactions in the relay log that have not yet been applied, they need to be replicated again from the primary pod.
However, if replication is delayed, the primary pod recreated by CLONE may not have the required binlogs.

**To Reproduce**
This occurs when there is a replication delay and all Pods and PVCs are rebuilt due to `nodeSelector` changes, etc.
If you reproduce it manually, it will look like this:

1. Stop SQL_THREAD on replica pod
`kubectl moco mysql -n mysql test -umoco-admin --index 2 -- -e "STOP SLAVE SQL_THREAD;"`

2. Add some data
`kubectl moco mysql -n mysql test -umoco-admin -- -e "CREATE DATABASE test;"`
`kubectl moco mysql -n mysql test -umoco-admin -- -e "CREATE TABLE t1 (i int);" test;"`
`kubectl moco mysql -n mysql test -umoco-admin -- -e "INSERT INTO test.t1 VALUES (1); COMMIT;"`

3. Re-create primary pod
`kubectl delete pvc -n mysql mysql-data-moco-test-1`

4. Execute switchover
`kubectl moco switchover -n mysql test`

5. Check replica pod (index=2)
`kubectl moco mysql -n mysql test -umoco-admin --index 2 -- -e "SHOW SLAVE STATUS;`

The following error occurs:
```
Got fatal error 1236 from master when reading data from binary log: 'Cannot replicate because the master purged required binary logs. Replicate the missing transactions from elsewhere, or provision a new slave from backup. Consider increasing the master's binary log expiration period. The GTID set sent by the slave is 'a99807e0-48b2-11ef-8363-e6f70f654277:1-1840331,
aa146c0a-48b2-11ef-bb40-22722a741e93:1-573934', and the missing transactions are 'aa146c0a-48b2-11ef-bb40-22722a741e93:573935-574176''
```

**Comment by ymmt2005** [comment] 2024-08-21 08:47
I'm afraid this is not a bug in MOCO because we cannot do anything if the primary is recreated.
Unless you have a good idea to address this, I'd like to close it.

**Comment by shunki-fujita** [comment] 2024-08-21 08:54
@ymmt2005 
How about delaying the execution of `CHANGE MASTER TO`?
Compare `gtid_purged` of the new primary with `gtid_executed` of the replica using `GTID_SUBSET()` and wait until there is no difference.

orchestrator seems to be doing something similar.
https://github.com/openark/orchestrator/blob/f0d685e0325322ba28f0eb79e3e64eceff241a30/go/inst/instance_topology.go#L589

**Comment by ymmt2005** [comment] 2024-08-21 09:07
@shunki-fujita not very sure.

I have a question about when this really happens.
If a primary pod is going to be recreated with CLONE, I guess another pod should become a new primary.
How come a recreated primary can continue to be the primary?

**Comment by shunki-fujita** [comment] 2024-08-21 09:34
@ymmt2005 
The problem is that the primary pod recreated by CLONE has no binlogs prior to the time of CLONE.

If all pods are re-created with CLONE, the process is as follows:
  1. recreate index=2 with CLONE from index=0
  2. recreate index=1 with CLONE from index=0
  3. switchover primary from index=0 to index=1
  4. recreate index=0 with CLONE from index=1

If there is a large replication delay at the time of 3., there will be a situation where binlogs that require index=2 are present at index=0 but not at index=1.
Waiting for switchover (specifically `CHANGE MASTER TO`) until a transaction that occurred before index=1 was created by CLONE is executed at index=2 should solve this problem.

**Comment by ymmt2005** [comment] 2024-08-21 10:14
@shunki-fujita Thank you, but my question is different.

I don't understand why such a recreated pod can continue to be the primary.
Normally, such a Pod should become a new replica because another Pod should
take over the primary role.

**Comment by ymmt2005** [comment] 2024-08-21 10:20
I mean, your step 3 in the issue body should trigger a fail over.

> To Reproduce
> Steps to reproduce the behavior:
> ...
> 3. Re-create primary pod

The steps in https://github.com/cybozu-go/moco/issues/731#issuecomment-2301604069 is totally different from what was explained in the issue body, so I'm confused. If all Pods are to be recreated, why don't you simply remove the MySQLCluster and recreate it from scratch?

**Comment by shunki-fujita** [comment] 2024-08-21 10:39
@ymmt2005 
Ahhhhh,.. the procedure in the text was a pseudo-reproduction of the replication delay.
Sorry for the confusion.

What actually happened was that the `nodeSelector` change caused all pods (and pvcs) to be re-created, resulting in the following comment situation:
https://github.com/cybozu-go/moco/issues/731#issuecomment-2301604069

**Comment by ymmt2005** [comment] 2024-08-21 10:41
Ah, gotcha. Thank you.

**Closed** 2024-09-04 04:31 UTC
Labels: bug
