### ISSUE TITLE
Will it support initializing SQL to create schema and  app users,  writing passwords to the secret in the future

### ISSUE THREAD

**Issue by sona-yuan** [cybozu-go/moco#718] opened 2024-07-08 03:20 UTC
## What

Will it support initializing SQL to create schema and  app users,  writing passwords to the secret in the future

## How

Describe how to address the issue.

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by ymmt2005** [comment] 2024-07-09 07:10
Duplicate of https://github.com/cybozu-go/moco/issues/349

**Comment by zeroalphat** [comment] 2024-07-09 07:33
Thank you for your question.
While we currently do not plan to implement this feature due to other priorities, we agree that it would be a nice addition.
We welcome pull requests if you would like to contribute by adding this feature.

**Comment by zeroalphat** [comment] 2024-07-10 07:03
@sona-yuan 
If you have any questions, please comment on #349 .
 Since this issue is a duplicate, I will close it.

**Closed by zeroalphat** 2024-07-10 07:03 UTC
