### ISSUE TITLE
Add arm images

### ISSUE THREAD

**Issue by bells17** [cybozu-go/moco#490] opened 2022-12-14 02:13 UTC
## What

Add arm images.

## How

use [buildx](https://docs.docker.com/engine/reference/commandline/buildx/) and [qemu](https://www.qemu.org/)

https://github.com/cybozu/ubuntu-base/pull/82

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by bells17** [comment] 2023-02-26 06:55
base images

- https://github.com/cybozu/neco-containers/pull/909
- https://github.com/cybozu/neco-containers/pull/914
- https://github.com/cybozu/neco-containers/pull/908

**Comment by masa213f** [comment] 2023-07-27 01:51
We cannot build the moco-backup image for linux/arm64.
We will addresse it in the future.

https://github.com/cybozu-go/moco/blob/v0.16.1/Dockerfile#L40
https://github.com/cybozu-go/moco/pull/522

**Comment by eplightning** [comment] 2023-08-06 00:41
Here's a quick workaround I found as I needed to run moco on ARM64 cluster:
https://github.com/eplightning/moco/commit/f1af0b8e5a8267177dbee817624b83b3c11cbda5

They publish arm64 binaries for "Linux - Generic" which seems to work fine on Ubuntu 20.04 .

Hopefully that helps someone.

**Comment by erinbit** [comment] 2024-03-11 18:27
Hi @zoetrope you closed this issue on the same day as release [0.20.1](https://github.com/cybozu-go/moco/compare/v0.20.0...v0.20.1) but I cannot see that there is an actual ARM container image with the release package? Just something listed as `unknown/unknown`. Am I missing something?
https://github.com/cybozu-go/moco/pkgs/container/moco

**Comment by ymmt2005** [comment] 2024-03-11 23:37
Confirmed. The image consists of linux/amd64 and unknown/unknown.
<img width="564" alt="image" src="https://github.com/cybozu-go/moco/assets/1461515/34a55a30-2b07-4889-bb3a-9d705d683888">

**Comment by ymmt2005** [comment] 2024-03-14 13:35
@morimoto-cybozu 
Was it due to the missing prebuilt image of mysqlshell for Ubuntu ARM64?
If so, I guess we can build it from the source code; it should be doable
as they provide a prebuilt ARM64 binary for Red Hat.
https://dev.mysql.com/get/Downloads/MySQL-Shell/mysql-shell-8.0.36-1.el9.aarch64.rpm

**Comment by eplightning** [comment] 2024-03-20 21:43
Linux - Generic glibc-2.28 builds on dev.mysql.com website also contain an ARM64 version which from my testing on personal cluster work perfectly fine as well.

**Comment by vholer** [comment] 2024-05-29 13:49
Thanks @eplightning for a hint, I have adapted the build in PR #681.

**Comment by ymmt2005** [comment] 2024-06-04 01:58
GitHub added ARM runners!
https://github.blog/2024-06-03-arm64-on-github-actions-powering-faster-more-efficient-build-systems/

**Closed** 2024-06-24 06:38 UTC
